### PR TITLE
Use miniconda in .travis.yml in order to speed up travis builds

### PR DESCRIPTION
**Pull request by samuela**

### CODE REVIEW

**Comment by samuela** [comment]
cc @pfhayes @iandewancker @mikemccourt

**Comment by samuela** [comment]
So it looks like numpy 1.10.1 isn't compatible with Python versions 2.6 and 3.3. Not sure why this didn't show up in the previous travis builds...

**Comment by mikemccourt** [comment]
Hmm, honestly, I guess (while we're on the upgrade train) we should
probably look into running numpy 1.11.1.  I think I would also advocate for
removing 2.6 and 3.3 from the supported versions, but I don't have an
opinion and will definitely defer to Patrick.

**Comment by samuela** [comment]
@mikemccourt Agreed. It's nice to stay up-to-date. Numpy version 1.11.1 also doesn't support Python 2.6 and 3.3.

**Comment by pfhayes** [comment]
is there any numpy that supports 2.6? if not let's upgrade numpy to latest and kill 2.6 support. if so we should probably just use the version of numpy that enables older users

**Comment by samuela** [comment]
Actually, this looks like it might be an incompatibility with the newest version of `conda`. We might be able to just stick to slightly out-of-date conda. Testing it out now...

**Comment by mikemccourt** [comment]
There's almost no need for numpy even in this package.  We could just
excise those locations and not make numpy an explicit requirement (it would
still be implicit since sklearn requires it, but then the person just has
to deal with their requirements, not ours).

Alternatively, we could just allow an older version of numpy.  it's not
really worth the fight if we're going to lose users.  But I would like
sigopt-api to get the upgrade, even if this doesn't.

**Comment by pfhayes** [comment]
I would also be happy with that

**Comment by samuela** [comment]
The story so far:

* Most recent conda version does not have support for Python versions 2.6 and 3.3. (Does anyone even use these anymore?)
* Previous conda versions support Python 3.3, but as far as I know not 2.6.
* If we are a little bit flexible with numpy versions, we can run 2.7, 3.3, 3.4, and 3.5 safely. Python 3.3 requires numpy 1.9.1, but all of the rest support numpy up to 1.11.1.

Looking through the code, we only barely use numpy and some of its most basically functionality at that. The extent of our use of numpy is

* `np.array` and `np.unique` at https://github.com/sigopt/sigopt_sklearn/blob/master/sigopt_sklearn/ensemble.py#L43, and
* `np.mean` and `np.std` at https://github.com/sigopt/sigopt_sklearn/blob/master/sigopt_sklearn/search.py#L319.

Therefore, I think we should be safe with nearly any numpy version. It seems like `numpy>=1.9` would be a reasonable adjustment.

**Comment by pfhayes** [comment]
sounds good to me. thanks sam!

**Comment by samuela** [comment]
Also, this is really just about the versions that we can run our travis builds on. I mean if a user really, really wants to run on Python 2.6, it would certainly be possible and would work out of the box. We just won't be actively testing on that (fossilized) version anymore.

**Comment by mikemccourt** [comment]
I'm fine with that.

**Comment by samuela** [comment]
How do we all feel about scikit-learn 0.16.x? Would `scikit-learn>=1.6` be ok?

**Comment by mikemccourt** [comment]
@iandewancker has a more informed opinion than myself.

**Comment by mikemccourt** [comment]
I do, however, think we are using something in scikit-learn 0.17.  I think
Ian pushed some stuff to joblib that is incorporated there.

**Comment by samuela** [comment]
Hmm, what about just dropping 3.3 then? That should make everything much, much easier. I think most people on Python 3 are on 3.5 at this point.

**Comment by pfhayes** [comment]
i'm fine with that

**Comment by samuela** [comment]
dope sauce. crossing my fingers and pushing again...

**Comment by samuela** [comment]
Ok, good to go?

**Comment by mikemccourt** [comment]
lgtm

**Pull request merged**
