### PR TITLE
fix bug introduced in sklearn 18 update

### PR DESCRIPTION
**Pull request by samuela**

### CODE REVIEW

**Comment by pfhayes** [comment]
will this still work properly for <= 17?

**Comment by samuela** [comment]
yeah the only difference is sklearn 17 allowed min_samples_split=1, but the latest version of 18 does not

**Comment by pfhayes** [comment]
do we know why? also, any reason why we bumped 4 -> 5?

**Comment by samuela** [comment]
well i think sklearn <= 17 just had a weird way of dealing with min_samples_split. It's not really possible to split a node on a single sample, but <= 17 did not error. I think it's just a matter of more cautious erroring in sklearn 18.

I bumped 4 -> 5 just so that the example would have the same interval width, but it shouldn't really matter.

**Comment by pfhayes** [comment]
ok, sounds good

**Pull request merged**
